# Generated by Django 6.0 on 2026-01-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "stock_price",
            "0005_remove_stockinfo_created_at_alter_stockinfo_market_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, db_index=True, verbose_name="생성 일자"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="테마명")),
                ("description", models.TextField(verbose_name="테마 설명/요약")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="분석 시각"),
                ),
            ],
            options={
                "verbose_name": "일일 테마",
                "verbose_name_plural": "일일 테마 목록",
                "db_table": "daily_theme",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThemeStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="편입 사유"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="stock_price.stockinfo",
                        verbose_name="종목",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="stock_theme.theme",
                        verbose_name="테마",
                    ),
                ),
            ],
            options={
                "verbose_name": "테마 편입 종목",
                "verbose_name_plural": "테마 편입 종목 목록",
                "db_table": "theme_stock",
            },
        ),
    ]
