# Generated by Django 6.0 on 2026-01-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_price", "0001_squashed_0004_remove_stockinfo_isin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockinfo",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="market",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="시장"
            ),
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="name",
            field=models.CharField(max_length=255, verbose_name="종목명"),
        ),
        migrations.AlterField(
            model_name="stockinfo",
            name="short_code",
            field=models.CharField(
                db_index=True, max_length=64, unique=True, verbose_name="단축코드"
            ),
        ),
    ]
