# Generated by Django 6.0 on 2025-12-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_alter_stockinfo_short_code'), ('api', '0003_alter_stockinfo_isin_alter_stockinfo_name_and_more'), ('api', '0004_remove_stockinfo_isin')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_info',
            },
        ),
    ]
